<?php
/**
 *  SFW - SimpleFrameWork
 *
 *  Copyright (C) 2019  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */
?>
<div class="modal fade" id="loginChangeDialogModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteDialogModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ändern</h5>
            </div>
            <div class="modal-body">
                Dein Passwort wurde erfolgreich geändert.
                Zum Abmelden klicke bitte oben rechts auf "<strong>abmelden</strong>".
            </div>
            <div class="modal-footer" margin-top: 12px;">
                <button id="btnChangeSuccess" type="button" class="btn btn-success btn-sm submit-form">okay</button>
            </div>
        </div>
    </div>
</div>

<div class="py-md-4 mx-auto" style="width: 35rem; padding-top: 3.5rem !important;">
    <div class="card card-block" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
        <h3 style="margin-bottom: 1.5rem;">Ändere hier Dein Password...</h3>
        <?php if($this->hash == ''): ?>
        <div class="row">
            <label for="oldpwd" class="col-sm-4 col-form-label">altes Passwort</label>
            <div class="col-sm-7">
                <input
                    id="oldpwd"
                    class="form-control form-control-sm"
                    type="password"
                    name="oldpwd"
                    size="30"
                    maxlength="30"
                    value=""
                />
                <div class="invalid-feedback"></div>
            </div>
        </div>
        <?php endif; ?>
        <div class="row">
            <label for="pwd" class="col-sm-4 col-form-label">neues Passwort</label>
            <div class="col-sm-7">
                <input
                    id="pwd"
                    class="form-control form-control-sm"
                    type="password"
                    name="pwd"
                    size="30"
                    maxlength="30"
                    value=""
                />
                <div class="invalid-feedback"></div>
            </div>
        </div>
        <div class="row">
            <label for="pwdr" class="col-sm-4 col-form-label">neues Passwort wiederholen</label>
            <div class="col-sm-7">
                <input
                    id="pwdr"
                    class="form-control form-control-sm"
                    type="password"
                    name="pwdr"
                    size="30"
                    maxlength="30"
                    value=""
                />
                <div class="invalid-feedback">Das Ändern des Passwortes schlug fehl!</div>
            </div>
        </div>
        <div class="modal-footer" style="border: 0; margin-top: 12px;">
            <button id="btnChange" type="button" class="btn btn-success btn-sm submit-form">
                setzen
            </button>
            <button id="btnCancel" type="button" class="btn btn-danger btn-sm">
                abbrechen
            </button>
        </div>
    </div>
</div>
<input type="hidden" id="lastPage" value="<?php echo($this->lastPage); ?>" />
<?php //TODO: Move this into js-file ?>

<script>
    <?php if($this->hash != ''): ?>
    $("#pwd").focus();
    <?php elye: ?>
    $("#oldpwd").focus();
    $('#oldpwd').keyup(function(e) {
        $('#oldpwd').removeClass('is-invalid');
    });
    <?php endif; ?>

    $('#pwd').keyup(function(e) {
        $('#pwd').removeClass('is-invalid');
    });

    $('#pwdr').keyup(function(e) {
        $('#pwdr').removeClass('is-invalid');
        if(e.keyCode === 13) {
            $('#btnChange').trigger('click');
        }
    });

    $('#btnChange').click(doChange);
    $('#btnCancel').click(returnToOrigin);

    function doChange() {
        $('#btnChange').prop('disabled', true);
        $('#btnCancel').prop('disabled', true);

        $.post(
            '?do=changePassword',
            {
                <?php if($this->hash == ''): ?>
                oldpwd: $('#oldpwd').val(),
                <?php endif;?>
                hash: '<?php echo($this->hash); ?>',
                pwdr: $('#pwdr').val(),
                pwd: $('#pwd').val(),
                xss: $('#xssToken').val()
            },
            success,
            "json"
        );
    }

    function success(data, textStatus) {
        $('#xssToken').val(data.xss);
        if(data.error) {
            $('#btnChange').prop('disabled', false);
            $('#btnCancel').prop('disabled', false);
            $('#oldpwd').addClass('is-invalid');
            let entries = data.data;
            for(let key in entries) {
                let item = $('[name=' + key + ']');
                if(entries[key].hint) {
                    item.addClass('is-invalid');
                    item.next().html(entries[key].hint);
                } else {
                    item.removeClass('is-invalid');
                }
            }
            return;
        }

        $('#loginChangeDialogModalCenter').modal({show: true})
        $('#btnChangeSuccess').click(returnToOrigin);
    }

    function returnToOrigin() {
        let url = $('#lastPage').val().split('?');
        window.location.href = url[0];
    };
</script>
