<div class="py-md-4 mx-auto" style="width: 35rem; padding-top: 3.5rem !important;">
<div class="alert alert-danger" role="alert">
    <h3 style="margin-bottom: 1.5rem;">Achtung: </h3>
    <p>
        Das Passwort kann nicht zurückgesetzt werden! Dies kann mehrere Ursachen haben:
    </p>
    <ul style="padding-left: 30px;">
        <li>Es wurden fehlerhafte Daten übergeben.</li>
        <li>Du bist nicht angemeldet.</li>
        <li>Es ist ein interner Fehler aufgetreten.</li>
    </ul>
    <p>
    Versuche es bitte erneut. Sollte das Problem weiterhin bestehen dann melde Dich bitte.
    </p>
</div>
</div>