<div class="py-md-4 mx-auto" style="width: 35rem; padding-top: 3.5rem !important;">
<div class="alert alert-danger" role="alert">
    <h3 style="margin-bottom: 1.5rem;">Achtung: </h3>
    <p>
    Es konnte kein neues Passwort erzeugt werden! Dies kann mehrere Ursachen haben:
    </p>
    <ul style="padding-left: 30px;">
        <li>Es wurden ein ungültiger Hash übergeben.</li>
        <li>Es wurde ein fehlerhafter Hash übergeben.</li>
        <li>Das Password wurde bereits zurückgesetzt.</li>
        <li>Es ist ein interner Fehler aufgetreten.</li>
        <li>Das Ablaufdatum wurde überschritten. Bitte achte darauf das Du innerhalb von <strong><?php echo($this->expire); ?></strong> reagierst!</li>
    </ul>
    <p>
    Versuche es bitte erneut. Sollte das Problem weiterhin bestehen dann melde Dich bitte.
    </p>
</div>
</div>