<?php

/**
 *  SFW - SimpleFrameWork
 *
 *  Copyright (C) 2013  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see
 *  http://www.gnu.org/licenses/agpl.txt.
 *
 */

?>
<div class="py-md-4 mx-auto" style="width: 35rem; padding-top: 3.5rem !important;">
    <div id="frmSuccess" class="card card-block " style="display:none; padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
        <h3 style="margin-bottom: 1.5rem;">Passwort rücksetzen</h3>
        <p>
            Bestätigungsnachricht wurde erfolgreich an <strong id="name"></strong> verschickt.
        </p>
        <p>
            Bitte klicke auf den Bestätigungslink den Du per E-Mail erhälst
            um Dein neues Passwort eingeben zu können.
        </p>
        <hr />
        <p>
            Der Bestätigungslink ist <strong id="expire"></strong>
            gültig. Solltest Du nicht innerhalb dieser Zeit auf den Link geklickt
            haben so wird Deine Anfrage automatisch gelöscht und Du kannst kein
            neues Passwort setzen!
        </p>
        <div class="modal-footer" style="border: 0; margin-top: 12px;">
            <button id="btnOkay" type="button" class="btn btn-success btn-sm submit-form">
                okay
            </button>
        </div>
    </div>
    <div id="frmQuery" class="card card-block" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
        <h3 style="margin-bottom: 1.5rem;">Passwort rücksetzen</h3>
        <p>
            Du hast Dein Passwort verbaselt? Hier hast Du die Möglichkeit, es wieder
            rückzusetzen.
        </p>
        <div class="row">
            <label for="user" class="col-sm-4 col-form-label">Benutzername</label>
            <div class="col-sm-7">
                <input
                    id="user"
                    class="form-control form-control-sm"
                    type="text"
                    name="user"
                    size="30"
                    maxlength="30"
                    value=""
                    title="Gib hier bitte Deinen Loginnamen ein"
                />
                <div class="invalid-feedback"></div>
            </div>
        </div>
        <div class="row">
            <label for="addr" class="col-sm-4 col-form-label">E-Mail</label>
            <div class="col-sm-7">
                <input
                    id="addr"
                    class="form-control form-control-sm "
                    type="text"
                    name="addr"
                    size="30"
                    maxlength="30"
                    value=""
                    title="Gib hier bitte Deine E-Mail-Adresse ein"
                />
                <div class="invalid-feedback"></div>
            </div>
        </div>
        <div class="modal-footer" style="border: 0; margin-top: 12px;">
            <button id="btnRequest" type="button" class="btn btn-success btn-sm submit-form">
                anfordern
            </button>
            <button id="btnCancel" type="button" class="btn btn-danger btn-sm">
                abbrechen
            </button>
        </div>
    </div>
</div>
<input type="hidden" id="lastPage" value="<?php echo($this->lastPage); ?>" />
<?php //TODO: Move this into js-file ?>
<script>
    $("#user").focus();
    $('#btnCancel').click(returnToOrigin);
    $('#btnRequest').click(doRequest);
    $('#btnOkay').click(returnToHome);

    $('#user').keyup(function(e) {
        $('#user').removeClass('is-invalid');
    });

    $('#addr').keyup(function(e) {
        $('#addr').removeClass('is-invalid');
        if(e.keyCode === 13) {
            $('#btnRequest').trigger('click');
        }
    });

    function doRequest() {
        $('#btnRequest').prop('disabled', true);
        $('#btnCancel').prop('disabled', true);

        $.post(
            '?do=request',
            {
                user: $('#user').val(),
                addr: $('#addr').val(),
                xss: $('#xssToken').val()
            },
            success,
            "json"
        );
    }

    function success(response, textStatus) {
        $('#xssToken').val(response.xss);

       if(response.error) {
            $('#btnRequest').prop('disabled', false);
            $('#btnCancel').prop('disabled', false);
            let entries = response.data;
            for(let key in entries) {
                let item = $('[name=' + key + ']');
                if(entries[key].hint) {
                    item.addClass('is-invalid');
                    item.next().html(entries[key].hint);
                } else {
                    item.removeClass('is-invalid');
                }
            }
            return;
        }

        $('#frmQuery').fadeOut('1250', function() {$('#frmSuccess').fadeIn('1250');});
        $('#name').html(response.data.name);
        $('#expire').html(response.data.expire);
    }

    function returnToOrigin() {
        let url = $('#lastPage').val().split('?');
        window.location.href = url[0];
    }

    function returnToHome() {
        window.location.href = '/login';
    }

</script>

