Hallo <?php echo($this->name) ?>,
<br />
<br />
Du hast ein neues Passwort angefordert.
<br />
Bitte klicke auf den folgen Aktivierungslink um die Anforderung zu bestätigen:
<br />
<br />
<a style="text-decoration: none; color: #0B8C37;" href="<?php echo($this->path); ?>"><?php echo($this->path); ?></a>
<br />
<br />
Solltest Du kein neues Passwort angefordert haben, dann lösche einfache diese Nachricht.
Dein bisheriges Passwort bleibt in diesem Fall unverändert.
<br />
<br />
