<?php

/**
 *  SFW2 - SimpleFrameWork
 *
 *  Copyright (C) 2018  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */

?>
<h1>User</h1>
<p>
    Hier kannst Du die User editieren
</p>
<div style="overflow-x: auto;">
<table class="mt-5 text-nowrap table-sm table table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col" colspan="2">Users</th>
            <th scope="col" style="text-align: right">
                <?php if($this->permission->createAllowed()): ?>
                <form id="<?php echo($this->getPathSimplified()); ?>" class="noshow">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Vorname" name="firstname" />
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Nachname" name="lastname" />
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="form-group">
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Geschlecht</div>
                            </div>
                            <select name="sex" class="form-control">
                                <option value="FEMALE">weiblich</option>
                                <option value="MALE">männlich</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Geburtstag</div>
                            </div>
                            <input type="date" class="form-control" placeholder="Geburtstag" name="birthdate" />
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">@</div>
                            </div>
                            <input type="email" class="form-control" placeholder="Email" name="email" />
                        </div>
                        <div class="invalid-feedback"></div>
                    </div>

                        Handy
                        Telefon

                    <div class="form-group checkbox">
                        <div class="form-check">
                            <input class="form-check-input" name="active" type="checkbox" id="active" value="1" />
                            <label class="form-check-label" for="active">
                                Aktiver Account
                            </label>
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>
                    <div class="form-group checkbox">
                        <div class="form-check">
                            <input class="form-check-input" name="admin" type="checkbox" id="admin" value="1" />
                            <label class="form-check-label" for="admin">
                                Administrativer Account
                            </label>
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>


                </form>
                <button
                    type="button"
                    class="btn btn-success btn-sm"
                    data-toggle="modal"
                    data-target="#createDialogModal"
                    data-url="<?php echo($this->getCurrentPath()); ?>"
                    data-form-id="<?php echo($this->getPathSimplified()); ?>"
                >Neuer Eintrag</button>
                <?php endif;?>
            </th>
        </tr>
    </thead>
    <tbody class="text-nowrap reload-data" data-url="<?php echo($this->getCurrentPath()); ?>">
    </tbody>
</table>
</div>
<div class="modificationDate">
Stand: <?php echo($this->modificationDate); ?>
</div>

