
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `{TABLE_PREFIX}_role` (
    `Id` int(11) UNSIGNED NOT NULL,
    `Name` varchar(256) NOT NULL,
    `Description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `{TABLE_PREFIX}_role` ADD PRIMARY KEY (`Id`);
ALTER TABLE `{TABLE_PREFIX}_role` MODIFY `Id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT;
