
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `{TABLE_PREFIX}_permission` (
    `RoleId` int(10) UNSIGNED NOT NULL,
    `PathId` int(10) UNSIGNED NOT NULL,
    `Permission` set('READ_OWN','READ_ALL','CREATE','UPDATE_OWN','UPDATE_ALL','DELETE_OWN','DELETE_ALL') NOT NULL DEFAULT 'READ_OWN'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `{TABLE_PREFIX}_permission` ADD UNIQUE KEY `RoleId` (`RoleId`,`PathId`);

