
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `sfw2_permission` (
  `RoleId` int(10) UNSIGNED NOT NULL,
  `PathId` int(10) UNSIGNED NOT NULL,
  `Permission` set('READ_OWN','READ_ALL','CREATE','UPDATE_OWN','UPDATE_ALL','DELETE_OWN','DELETE_ALL') NOT NULL DEFAULT 'READ_OWN'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `sfw2_permission`
  ADD UNIQUE KEY `RoleId` (`RoleId`,`PathId`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
