
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `{TABLE_PREFIX}_user_role` (
    `UserId` int(10) UNSIGNED NOT NULL,
    `RoleId` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `{TABLE_PREFIX}_user_role` ADD UNIQUE KEY `key` (`UserId`,`RoleId`);

